project:
  type: website
  output-dir: docs

website:
  title: "BCB521"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - syllabus.qmd

  

    
  

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true



