---
title: "BCB 521:: Communicating with Data"
listing:
  contents: posts
  sort: "date desc"
  type: grid
  categories: true
  sort-ui: true
  filter-ui: true
page-layout: full
title-block-banner: true
---

# **// About**

Students are taught writing and presentation skills to improve their communication of data-driven insights to specialist and lay audiences. The course emphasizes reproducible research practices, including literate programming (Quarto / Markdown) and version control (GitHub). Course content includes the conceptual foundations of communicating with data along with written and verbal assignments using data sets individualized to each student’s interest. The course is designed to be "discipline agnostic" - each student is encouraged to use their own data, or public data sets that they deem important / interesting. 

## Quick Links

[SYLLABUS](syllabus.qmd)

[Barrie's GitHub](https://github.com/ProfessorPolymorphic){target="_blank"}

[BCB521 Repository](https://github.com/ProfessorPolymorphic/BCB521){target="_blank"}

### Student Repositories



## Learning Resources

[The Functional Art](http://www.thefunctionalart.com)

[GGSIDE!](https://www.business-science.io/code-tools/2021/05/18/marginal_distributions.html) A companion to `ggplot` for making side plots! COOL!

[Awesome Quarto:](https://github.com/mcanouil/awesome-quarto){target="_blank"} A potentially interesting repository of Quarto documents, talks, tools, examples, etc.

[The MockUp Blog - TABLES!](https://themockup.blog/posts/2022-06-13-gtextras-cran/){target="_blank"} This blog post explores the R packages `gt` and `gtextras` which will help us up our table game!

[Riffomonas Project](https://www.youtube.com/@Riffomonas/featured){target="_blank"}: Pat Schloss is a [Professor at the University of Michigan](https://www.schlosslab.org){target="_blank"}. The Riffomonas Project is his Youtube channel, which has HUNDREDS of easy to follow and amazingly useful instructional videos on R, ggplot, version control, and literate programming.

[Dr. Tamara Munzner's Website:](https://www.cs.ubc.ca/~tmm/){target="_blank"} It isn't fancy, but Dr. Munzner's website has tons of resources from her textbook and the many data visualization courses she has offered. This includes recorded lectures that align directly with the chapters of the text, much like what we are using.

[Cheat Sheets:](https://posit.co/resources/cheatsheets/){target="_blank"} So many visual guides for many R packages, including the tidyverse, ggplot, dplyr, etc.

[Learning Vis Tools: Teaching Data Visualization Tutorials](https://ieeexplore.ieee.org/document/8933751){target="_blank"} An interesting paper for discussion as we forge the structure for this class.

# **// Posts**
