---
title: "SYLLABUS 2024"
author: "Barrie Robison"
date: "2024-08-12"
---

# BCB 521: Communicating with Data

**Barrie D. Robison**

**Fall 2024**

## Course Description

Students are taught writing and presentation skills to improve their communication of data-driven insights to specialist and lay audiences. The course emphasizes reproducible research practices, including literate programming (Quarto / Markdown) and version control (GitHub). Course content includes the conceptual foundations of communicating with data along with written and verbal assignments using data sets individualized to each student’s interest. The course is designed to be "discipline agnostic" - each student is encouraged to use their own data, or public data sets that they deem important / interesting. 

## Course Objectives

Students completing this course will be able to:

1.  Identify, understand, and describe the critical characteristics, needs, and expectations of the various audiences with whom they will communicate.

2. Develop and apply effective writing and presentation skills to communicate data-driven insights clearly and impactfully to both specialist and general audiences.

3. Implement reproducible research practices using literate programming (Quarto/Markdown) and version control (GitHub) to enhance the transparency and reproducibility of their work.

4. Create compelling narratives around data that are tailored to specific disciplines while remaining accessible to interdisciplinary audiences.

5. Critically evaluate and apply appropriate data visualization techniques to support written and verbal communications, enhancing the accessibility of complex data analysis results.

## Required Readings

As assigned.  There is not a required textbook for this class.

## Course Policies

### GRADING

40% of your grade will be determined by homework exercises related to each course unit.

20% of your grade will be determined by a mid term project (which would be a great item to include in your Data Science Portfolio).

20% of your grade will be determined by a final project (which would be great item to include in your Data Science Portfolio).

20% of your grade will be determined by participation in class discussions and individual meetings with the instructor.

GRADING SCALE: The grading scale is standard: A (90 -100 %), B (89 - 80 %), C (79 - 70 %), D (69-60 %), F( below 60 %).

### ATTENDANCE POLICY

Missing a scheduled class session is at your discretion. I will be posting all the course materials online. If a discussion or in-class exercise occurs and you miss it, you will lose those participation points. There is no way to make up those points.

### LATE ARRIVAL OF PROFESSOR POLICY

The R Markdown template I used for this syllabus was created by Dr. Steven V. Miller at Stockholm University. It contained this section, which I found amusing and have therefore retained. Professor Miller's current university asks professors to have policies written into their syllabus about what students should do if the professor is more than 15 minutes late to class. Here is my version of that policy:

I will inform students via e-mail in advance of class if class is cancelled for the day. Events that might create such a scenario include travel obligations that emerged after the semester has begun, a family emergency that encompasses multiple days, or some other thing. I will also contact our department secretary in emergent situations, such as something happening on the way to work. Failing that, assume the worst. Alien abduction, the return of one or more Old Ones to our plane, or some kind of attack by wizards are all viable explanations for my inability to attend class. I ask that the students make sure that my story gets the proper treatment on the "Mr. Ballen" YouTube channel. I also ask that my story be narrated by Morgan Freeman and that the role of me in the made for TV movie be played by Keanu Reeves or Danny DeVito.

### MAKE UP EXAM POLICY

The bad news is that there are NO make-ups for missed exams. Don't bother asking. The good news is that there aren't any exams.

### ACADEMIC DISHONESTY POLICY

All students are expected to uphold the highest standards of academic honesty. This includes but is not limited to: not cheating, not using the ideas of others without giving appropriate credit (including AI tools), and not falsifying data. Any incident of academic dishonesty will be handled according to the guidelines of the University of Idaho.

## Class Schedule

```{r}

library(readxl)
Schedule <- read_excel("Schedule.xlsx")

knitr::kable(Schedule, caption = '')
```
